---
- name: Install sysstat, containerd, kubelet, kube-proxy, kubeadm, kubectl
  hosts: all
  become: yes
  tasks:

    - name: Install sysstat
      apt:
        name: sysstat
        state: present
        update_cache: yes

    - name: Load required kernel modules
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter

    - name: Apply kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Set sysctl params
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl
      command: sysctl --system

    - name: Install common dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install containerd
      apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart containerd
      systemd:
        name: containerd
        enabled: yes
        state: restarted

    - name: Add Kubernetes APT key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repo
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install kubelet, kubeadm, kubectl, kube-proxy version 1.30.0
      apt:
        name:
          - kubelet=1.30.0-00
          - kubeadm=1.30.0-00
          - kubectl=1.30.0-00
          - kube-proxy=1.30.0-00
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      apt:
        name: "{{ item }}"
        state: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
        - kube-proxy

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
